---
name: make test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        perl: ["5.42", "5.24", "5.8"]
        exclude:
          - os: "windows-latest"
            perl: "5.8"
      fail-fast: false
    env:
      MAKECMD: ${{ (matrix.os == 'windows-latest' && 'gmake') || 'make' }}
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          enable-modules-cache: false
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: |
          touch cpanfile
          echo 'requires "Net::CIDR::Lite" => "0";' >> cpanfile
          echo 'requires "Socket" => "1.87";' >> cpanfile
          echo 'requires "Test::More" => "0.88";' >> cpanfile
          echo 'requires "Test::Pod" => "1.00";' >> cpanfile
          echo 'requires "version" => "0";' >> cpanfile
          cpanm --insecure --installdeps .
      - name: Build module
        run: |
          perl Makefile.PL
          ${{ env.MAKECMD }}
      - name: Run tests
        run: |
          ${{ env.MAKECMD }} test TEST_VERBOSE=1
